import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Component/Navbar";
import Footer from "./_Component/Footer";
import { Toaster } from "@/components/ui/sonner"
import Context from "./_Component/Context";
import Contextprovider from "./_Component/CountItem";
import ContextProvider from "./_Component/CountItem";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <Context>
          <ContextProvider>
 <Navbar/>
        {children}
        <Footer/>
        <Toaster/>
          </ContextProvider>

        </Context>



 
 
      
      </body>
    </html>
  );
}
